server:
  grpc_port: 50051
  http_port: 8080
  grpc_gateway_port: 8082
  
database:
  host: "localhost"
  port: 5432
  username: "admin"
  password: "admin"
  name: "geo"
  ssl_mode: "disable"

resit:
  host: "localhost"
  port: 6379
  database: 0

kafka:
  host: "localhost"
  port: 9092
